version: "3.9"
services:
  client-app:
    image: client-app
    environment:
      - REACT_APP_CLIENT_ARRAYS_SERVICE_HOST=localhost
      - REACT_APP_CLIENT_ARRAYS_SERVICE_PORT=5000
      - REACT_APP_CLIENT_ARRAYS_SERVICE_PROTOCOL=http
    ports:
      - "3000:3000"
  client-arrays-service:
    image: client-arrays-service
    environment:
      - LOG_SERVICE_HOST=log-service
      - LOG_SERVICE_PORT=5001
      - LOG_SERVICE_PROTOCOL=http
    ports:
      - "5000:5000"
  log-service:
    image: log-service
    ports:
      - "5001:5001"
